version: '3'
services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    container_name: api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - 'db'
    environment:
      - TZ=Asia/Tokyo

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf/my.conf:/etc/mysql/conf.d/my.cnf
      - ./mysql/store:/var/lib/mysql
      - ./mysql/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=sushi_admin
      - MYSQL_PASSWORD=passw0rd
      - MYSQL_DATABASE=SushiOrderDB
      - TZ=Asia/Tokyo
    restart: always
